class Condominio {
    constructor () {
        this.arrayCond = [

//      CONDOMÍNIOS DE FORTALEZA

            { nome: "LOCKTEC", lat: "-3.73030", lon: "-38.48041", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Oliveira Viana', num: '77', bairro: "Vicente Pinzon", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "ÁGUA FRIA", lat: "-3.7728741862041844", lon: "-38.46988156256665", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Cidade Ecológica', num: '80', bairro: "Edson Queiroz", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "ALBERTO VIANA", lat: "-3.72639", lon: "-38.50235", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Silvia Jatahy', num: '160', bairro: "Aldeota", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "ANGRA", lat: "-3.72425", lon: "-38.48632", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Senador Machado', num: '185', bairro: "Mucuripe", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "ANTÚRIOS", lat: "-3.742", lon: "-38.50338", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Joaquim Nabuco', num: '1889', bairro: "Aldeota", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "ARNALDO BERNHARD", lat: "-3.7407533873481107", lon: "-38.494665089058415", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Paula Ney', num: '444', bairro: "Aldeota", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "ARTHUR BERNARDES", lat: "-3.80975", lon: "-38.47024", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Avenida Presidente Arthur Bernardes', num: '2757', bairro: "José de Alencar", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "ÁSIA IMPERIAL", lat: "-3.80825", lon: "-38.47116", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Rafael Tobias', num: '2185', bairro: "José de Alencar", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "ASPEN", lat: "-3.74242", lon: "-38.49181", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Travessa Monsehor Catão', num: '1200', bairro: "Aldeota", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "ATALAIA", lat: "-3.72812", lon: "-38.49893", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Ana Bilhar', num: '123', bairro: "Meireles", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "ATHALANTA", lat: "-3.72947", lon: "-38.49408", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Leonardo Mota', num: '340', bairro: "Meireles", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "ATALANTA", lat: "-3.81526", lon: "-38.46841", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Avenida Odilon Guimarães', num: '3740', bairro: "Curió", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "AVALLON HILL", lat: "-3.74853", lon: "-38.52672", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Monsenhor Otávio de Castro', num: '677', bairro: "Fátima", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "BARÃO DE ARACATI", lat: "-3.732836596779856", lon: "-38.511850547193426", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Barão de Aracati', num: '1291', bairro: "Aldeota", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "BARCELONA", lat: "-3.73297", lon: "-38.51442", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Antônio Augusto', num: '1450', bairro: "Meireles", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "BARRAMAR E BARRASOL", lat: "-3.73236", lon: "-38.47993", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Engenheiro Santana Junior', num: '333', bairro: "Vicente Pinzon", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "BELIZE", lat: "-3.7612067962012357", lon: "-38.49033457663506", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Rua Professor Jacinto Botelho', num: '425', bairro: "Edson Queiroz", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "BELLE MONDUBIM", lat: "-3.83446", lon: "-38.58757", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Nossa Senhora Aparecida', num: '300', bairro: "Aracapé", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "BERNARD TAPIE", lat: "-3.72913", lon: "-38.49656", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Ana Bilhar', num: '379', bairro: "Meireles", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "BERNINE", lat: "-3.7418", lon: "-38.47852", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Joaquim Lima', num: '950', bairro: "Papicu", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "BERNINI", lat: "-3.72958", lon: "-38.50728", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Avenida Rui Barbosa', num: '733', bairro: "Meireles", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "BESANÇON", lat: "-3.72978", lon: "-38.49288", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Vicente Leite', num: '389', bairro: "Meireles", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "BRISAS DO JACAREY", lat: "-3.7997", lon: "-38.49524", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Chico Lemos', num: '1405', bairro: "Parque Iracema", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "BROMELIAS", lat: "-3.80796", lon: "-38.53531", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Rua das Carnaúbas', num: '560', bairro: "Passaré", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "BROOKSVILLE", lat: "-3.74111", lon: "-38.49242", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Coronel Jucá', num: '1000', bairro: "Aldeota", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "BUCKINGAHN", lat: "-3.72608", lon: "-38.50164", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'José VIlar', num: '180', bairro: "Meireles", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "CARMEL ATLANTICO", lat: "-3.74693", lon: "-38.45665", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Avenida Trajano de Medeiro', num: '3233', bairro: "Vicente Pinzon", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "CASTELLAR II", lat: "-3.81077", lon: "-38.52277", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Crisanto Arruda', num: '150', bairro: "Passaré", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "CASTELLAR III", lat: "-3.81341", lon: "-38.52847", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Pedro Verissimo', num: '3535', bairro: "Passaré", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "CATAMARÃ", lat: "-3.72920", lon: "-38.49087", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Avenida Senador Virgilio Távora', num: '30', bairro: "Meireles", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "COLINA DE ROMA", lat: "-3.72821", lon: "-38.48914", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Barbalha', num: '300', bairro: "Meireles", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "CONCORDIA", lat: "-3.7485520777941113", lon: "-38.51524919555188", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Soriano Albuquerque', num: '575', bairro: "Joaquim Távora", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "COSTA BARRETO", lat: "-3.74714", lon: "-38.50504", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Joaquim Nabuco', num: '2485', bairro: "Dionisio Torres", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "CYNTHIA", lat: "-3.7471209534637", lon: "-38.46760909518526", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Vilebaldo Aguiar', num: '2300', bairro: "Cocó", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "DAMASCO", lat: "-3.76528", lon: "-38.55102", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Irmã Bazet', num: '760', bairro: "Montese", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "DIVA MARINHO", lat: "-3.74654", lon: "-38.48406", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Arquiteto Reginaldo Rangel', num: '55', bairro: "Cocó", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "DOM BOSCO", lat: "-3.80836", lon: "-38.56875", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: '26° Batalhão', num: '291', bairro: "Mondubim", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "ETA CARENAE", lat: "-3.7299", lon: "-38.49409", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Leonardo Mota', num: '303', bairro: "Meireles", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "EUROPA BOULEVARD", lat: "-3.8033368158989425", lon: "-38.47320875034511", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Bill Cartaxo', num: '1725', bairro: "Sapiranga", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "EUSEBIO VILLE", lat: "-3.87370", lon: "-38.46511", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Luiz Pio Campina', num: '41', bairro: "Tamatanduba", cidade: "Eusébio", sigla: "CE" } },
            { nome: "FLAMBOYANT", lat: "-3.79012", lon: "-38.46516", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Nadir Saboya', num: '750', bairro: "Sapiranga", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "FREITAS", lat: "-3.74568", lon: "-38.48011", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Andrade Furtado', num: '1060', bairro: "Cocó", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "G TORRES", lat: "-3.72551", lon: "-38.5107", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Idelfonso Albano', num: '525', bairro: "Meireles", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "GENOVAVENEZA", lat: "-3.734", lon: "-38.49113", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Professor Dias da Rocha', num: '482', bairro: "Meireles", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "GERMANA GURGELL III", lat: "-3.8605646354038914", lon: "-38.46471630867126", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Avenida José Moraes de Almeida', num: '844', bairro: "Coaçu", cidade: "Eusébio", sigla: "CE" } },
            { nome: "GIARDINO DI FAZANO", lat: "-3.7612506952300575", lon: "-38.48392683861385", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Ministro Eduardo Ellery Barreira', num: '60', bairro: "Guararapes", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "HELDER LEITE JUNIOR", lat: "-3.80394", lon: "-38.53799", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Rua dos Sabías', num: '103', bairro: "Passaré", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "HERÓIS DO ACRE", lat: "-3.8032655070187755", lon: "-38.53563360023965", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Avenida Heróis do Acre', num: '775', bairro: "Passaré", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "HILMAR FALÇÃO", lat: "-3.7254", lon: "-38.51214", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Antônio Augusto', num: '570', bairro: "Meireles", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "HYDE PARK", lat: "-3.74467", lon: "-38.50211", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Dom Expedito Lopes', num: '2577', bairro: "Dionisio Torres", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "IDEZITH CÂMARA", lat: "-3.79065", lon: "-38.46074", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'José Moacir Bezerra', num: '1111', bairro: "Sapiranga", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "ILHA BELA", lat: "-3.75611", lon: "-38.53244", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'General Silva Junior', num: '800', bairro: "Fátima", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "IMPERIAL MARAPONGA", lat: "-3.78753290726735", lon: "-38.562162723927166", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'José Meneleu', num: '760', bairro: "Itaperi", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "IPANEMA", lat: "-3.72706", lon: "-38.46558", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Visconde de Cairu', num: '720', bairro: "Jardim Guanabara", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "IRACEMA ROCHA", lat: "-3.70454", lon: "-38.59143", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Avenida Coronel Carvalho', num: '240', bairro: "Vila Velha", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "ISOLA DI CAPRI", lat: "-3.72874", lon: "-38.50308", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Tenente Amauri Pi', num: '380', bairro: "Aldeota", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "ITAMARACA", lat: "-3.74392", lon: "-38.47973", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Doutor Gilberto Studart', num: '955', bairro: "Cocó", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "ITAPEMA", lat: "-3.7371177377443106", lon: "-38.47361689147016", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Amélia Benebien', num: '333', bairro: "Papicu", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "JARDIM DAS FLORES", lat: "-3.85872", lon: "-38.64347", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Antônio Perreira do Nascimento', num: '160', bairro: "Luzano Viana", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "JARDINS PASSARÉ", lat: "-3.80324", lon: "-38.53591", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Avenida Heróis do Acre', num: '801', bairro: "Passaré", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "JARDINS SAMARIA I", lat: "-3.80476", lon: "-38.53285", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Avenida Prudente Brasil', num: '180', bairro: "Passaré", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "JEOVÁ MATOS", lat: "-3.74285", lon: "-38.48698", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Avenida Engenheiro Santana Junior', num: '2360', bairro: "Cocó", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "JEQUITIBA", lat: "-3.81963", lon: "-38.49808", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Madre Ana Couto', num: '401', bairro: "Messejana", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "JOSE CARLOS DE PINHO", lat: "-3.730594347550627", lon: "-38.49748466253304", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Visconde de Mauá', num: '501', bairro: "Meireles", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "KARIBE", lat: "-3.73516", lon: "-38.48291", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Raimundo Oliveira Filho', num: '153', bairro: "Varjota", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "KELLY", lat: "-3.74117", lon: "-38.56687", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Moreira de Sousa', num: '525', bairro: "Parquelândia", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "LA VIDA PARQUE", lat: "-3.90915", lon: "-38.44785", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Avenida Noe Leite de Freitas', num: '393', bairro: "Lagoinha", cidade: "Eusébio", sigla: "CE" } },
            { nome: "LAGO JACAREY", lat: "-3.79868", lon: "-38.49292", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Máximo Linhares', num: '299', bairro: "Cambeba", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "LARA", lat: "-3.72976", lon: "-38.49462", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Ana Bilhar', num: '601', bairro: "Meireles", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "LE MAN'S", lat: "-3.74846", lon: "-38.46742", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Manuel Queiros', num: '460', bairro: "Cocó", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "LIBERTY PLACE", lat: "-3.73254", lon: "-38.48451", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Tavares Coutinho', num: '2050', bairro: "Varjota", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "LIDIA BRIGIDO - OURO BRANCO", lat: "-3.78916", lon: "-38.48484", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Lidia Brigido', num: '151', bairro: "Parque Manibura", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "LIDIANE", lat: "-3.7383132609935616", lon: "-38.56344639910428", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Amadeu Furtado', num: '289', bairro: "Parquelândia", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "LISBOA", lat: "-3.74084", lon: "-38.5042", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Tibúrcio Cavalcante', num: '1848', bairro: "Aldeota", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "LIVIO ARRUDA", lat: "-3.7302294578879813", lon: "-38.49435522810906", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Leonardo Mota', num: '400', bairro: "Meireles", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "LOS ANGELES", lat: "-3.73570", lon: "-38.48154", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Paulo Morais', num: '303', bairro: "Varjota", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "LUIS TEIXEIRA", lat: "-3.7377", lon: "-38.51041", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Catão Mamede', num: '237', bairro: "Aldeota", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "LUIZ VIDAL", lat: "-3.72766", lon: "-38.51138", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Idelfonso Albano', num: '777', bairro: "Meireles", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "MANSÃO BARCELONA", lat: "-3.73148", lon: "-38.47892", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Professor Heráclito', num: '313', bairro: "Vicente Pinzon", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "MAR DEL PLATA", lat: "-3.73223", lon: "-38.57101", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Edgar Falcão', num: '130', bairro: "Presidente Kennedy", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "MARBELA", lat: "-3.74924", lon: "-38.5314", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Mário Mamede', num: '1300', bairro: "Fátima", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "MARC CHAGALL", lat: "-3.74418", lon: "-38.49091", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Caroline Sucupira', num: '1478', bairro: "Aldeota", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "MARIA CANDIA PINHEIRO", lat: "-3.72823", lon: "-38.49196", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Paula Barros', num: '345', bairro: "Meireles", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "MARIA JOSE", lat: "-3.73765", lon: "-38.51707", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'João Cordeiro', num: '1991', bairro: "Piedade", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "MARIA NATIVIDADE", lat: "-3.73785", lon: "-38.51442", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Barbara de Alencar', num: '1101', bairro: "Aldeota", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "MARNE CAVALCANTE LINS", lat: "-3.75485", lon: "-38.52591", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Campo Amor Rocha', num: '188', bairro: "Fátima", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "MARQUES DE VALÊNCIA", lat: "-3.733173131364795", lon: "-38.45727162334497", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Avenida Zeze Diogo', num: '2970', bairro: "Praia do Futuro", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "MAXMILIAN", lat: "-3.7379208005077174", lon: "-38.48972807207252", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Maria Tomásia', num: '1271', bairro: "Aldeota", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "MEGAVILLE", lat: "-3.74803", lon: "-38.58533", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Rui Monte', num: '1070', bairro: "Dom Lustosa", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "MEIRELES COMPACT", lat: "-3.72657", lon: "-38.50806", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Deputado Moreira da Rocha', num: '557', bairro: "Meireles", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "MELISSA", lat: "-3.743404172602655", lon: "-38.50650617719093", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Dom Expedito Lopres', num: '1956', bairro: "Aldeota", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "MIRTES ANTUNES", lat: "-3.801400504981381", lon: "-38.527831976784974", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Fiscal Assis Saraiva', num: '1001', bairro: "Boa Vista", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "MIRZA LINHARES", lat: "-3.7448351478755186", lon: "-38.48233863550432", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Andrade Furtado', num: '799', bairro: "Cocó", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "MOISES MENDES", lat: "-3.74819", lon: "-38.51044", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Barão Studart', num: '2765', bairro: "Dionisio Torres", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "MONTE VERDE", lat: "-3.82609", lon: "-38.47599", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Avenida Professor José Arthur de Carvalho', num: '400', bairro: "Lagoa Redonda", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "MONTE VILLAGE", lat: "-3.800775965006298", lon: "-38.56759031296393", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Rúbens Monte', num: '520', bairro: "Jardim Cearense", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "MONTERREY", lat: "-3.73601", lon: "-38.50985", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Afonso Celso', num: '225', bairro: "Aldeota", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "NEBADON", lat: "-3.75418", lon: "-38.52889", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Avenida Depudato Oswaldo Studart', num: '362', bairro: "Fátima", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "NORTH VILLAGE", lat: "-3.7296208747570465", lon: "-38.56555506798795", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Margarida Maria', num: '1000', bairro: "Presidente Kennedy", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "NORTHVILLE", lat: "-3.73693", lon: "-38.54767", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Padre Guerra', num: '417', bairro: "Parque Araxá", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "NOSSA SENHORA APARECIDA", lat: "-3.76558", lon: "-38.54779", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Venezuela', num: '120', bairro: "Montese", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "NOVO LINDO PARQUE", lat: "-3.7531284668555287", lon: "-38.502962406899805", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Isac Amaral', num: '751', bairro: "Aldeota", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "OMMI", lat: "-3.73354", lon: "-38.49297", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Pereira Valente', num: '945', bairro: "Meireles", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "PALAZZIO TICIANA", lat: "-3.74048", lon: "-38.49515", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Paula Ney', num: '365', bairro: "Aldeota", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "PARAÍSO", lat: "-3.72828", lon: "-38.48198", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Canindé', num: '797', bairro: "Varjota", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "PARAÍSO DA MARAPONGA", lat: "-3.79661", lon: "-38.56744", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Francisco Glicéiro', num: '722', bairro: "Maraponga", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "PARK VILLAGE", lat: "-3.77441", lon: "-38.49187", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Maria Alice Ferraz', num: '1314', bairro: "Engenheiro Luciano Cavalcante", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "PARNASO", lat: "-3.73201", lon: "-38.50182", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Pereira Filgueiras', num: '2400', bairro: "Aldeota", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "PARQUE DOS COQUEIROS", lat: "-3.7892", lon: "-38.57228", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Avenida Bibio Frota', num: '571', bairro: "Parangaba", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "PAULO QUEZADO", lat: "-3.73302", lon: "-38.4678", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Avenida Engenheiro Luiz Vieira', num: '320', bairro: "Praia do Futuro I", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "PETIT PALAIS", lat: "-3.72532", lon: "-38.50824", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Carlos Vasconcelos', num: '355', bairro: "Meireles", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "PIAZZA NOVANA", lat: "-3.727011159683257", lon: "-38.55264964739419", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Henrique Autran', num: '673', bairro: "Monte Castelo", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "PINE TOWER", lat: "-3.759096482176029", lon: "-38.48998252200003", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Justino Café Neto', num: '194', bairro: "Guararapes", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "PORT PRINCE", lat: "-3.7325", lon: "-38.50153", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Tibúrcio Cavalcanti', num: '838', bairro: "Aldeota", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "PORTAL DOS VENTOS", lat: "-3.7911884605677226", lon: "-38.45911646558612", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Corrêa Lima', num: '2150', bairro: "Edson Queiroz", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "PORTO PRINCIPE", lat: "-3.8084", lon: "-38.53548", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Rua das Carnaúbas', num: '570', bairro: "Passaré", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "PRUDENTE BRASIL", lat: "-3.8032423283238384", lon: "-38.535179187121464", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Avenida Heróis do Acre', num: '725', bairro: "Passaré", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "RAIMUNDO MORAES", lat: "-3.75082", lon: "-38.56065", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Virato Ribeiro', num: '744', bairro: "Bela Vista", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "RAMOS DE LUZ", lat: "-3.7523", lon: "-38.52079", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Avenida Visconde do Rio Branco', num: '3556', bairro: "Fátima", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "RECANTO DOS VENTOS", lat: "-3.8311", lon: "-38.48809", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Pedro II', num: '300', bairro: "Messejana", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "RENATA JATAHY", lat: "-3.7547401037473254", lon: "-38.51597410915568", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Fiscal Vieira', num: '3800', bairro: "São João do Tauape", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "RENATA ROCHA", lat: "-3.70785", lon: "-38.59484", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: '27', num: '190', bairro: "Vila Velha", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "RIVADAVIA", lat: "-3.74709", lon: "-38.46706", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Manuel Queiroz', num: '260', bairro: "Cocó", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "RIVER PARK", lat: "-3.76061", lon: "-38.47898", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Professor Wilson Aguiar', num: '357', bairro: "Edson Queiroz", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "RIVIEIRA", lat: "-3.72563", lon: "-38.46254", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Visconde de Cairu', num: '200', bairro: "Vicente Pinzon", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "SAFIRA", lat: "-3.73522", lon: "-38.46924", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Coronel José Aurelio Câmara', num: '1400', bairro: "Vicente Pinzon", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "SAINT MORITZ", lat: "-3.74643", lon: "-38.47511", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Bento Albuquerque', num: '1550', bairro: "Cocó", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "SALINAS", lat: "-3.75834", lon: "-38.49079", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Professor Jacinto Botelho', num: '120', bairro: "Guararapes", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "SALUSTIANO", lat: "-3.76048", lon: "-38.48562", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Francisco Xerez', num: '200', bairro: "Guararapes", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "SAN ISIDRO", lat: "-3.73655", lon: "-38.53249", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Senador Pompeu', num: '2030', bairro: "José Bonifácio", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "SAN MATHEUS", lat: "-3.79047", lon: "-38.46378", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Olegário Memória', num: '2973', bairro: "Sapiranga", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "SAN MATHEUS", lat: "-3.73615", lon: "-38.52287", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Rocha Lima', num: '135', bairro: "Centro", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "SAN THIAGO", lat: "-3.73357", lon: "-38.4791", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Avenida Engenheiro Alberto Sá', num: '231', bairro: "Papicu", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "SANTA CLARA", lat: "-3.7534435395608066", lon: "-38.571102851724746", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Piauí', num: '1390', bairro: "Pici", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "SANTOS DUMONT", lat: "-3.74171", lon: "-38.48183", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Avenida Santos Dumont', num: '5600', bairro: "Aldeota", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "SANTOS DUMONT CENTER", lat: "-3.7306", lon: "-38.51546", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Avenida Santos Dumont', num: '905', bairro: "Centro", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "SANT GERARD", lat: "-3.7346733879565424", lon: "-38.568486434630344", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Rua 3', num: '255', bairro: "Presidente Kennedy", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "SAINT EXUPERY", lat: "-3.7287092479905777", lon: "-38.48816563310773", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Pedro Rufino', num: '135', bairro: "Varjota", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "SARAH", lat: "-3.73231", lon: "-38.47895", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Pascoal de Castro Alves', num: '332', bairro: "Vicente Pinzon", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "SÃO PAULO", lat: "-3.72153", lon: "-38.54106", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Avenida Filomeno Gomes', num: '733', bairro: "Jacarecanga", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "SECULUS", lat: "-3.81042", lon: "-38.52558", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Doutor Pedro Sampaio', num: '250', bairro: "Passaré", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "SOPHIA MARINHO", lat: "-3.72549", lon: "-38.50589", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Thomaz Pompeu / Avenida Rui Barbosa', num: '261/323', bairro: "Meireles", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "STADIUM RESIDENCE", lat: "-3.8136075538281475", lon: "-38.52248876013132", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Amâncio Pereira', num: '421', bairro: "Passaré", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "STUDART PLACE", lat: "-3.747149764138053", lon: "-38.469690000575", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Doutor Gilberto Studart', num: '2125', bairro: "Cocó", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "SUN CITY", lat: "-3.7376621073449687", lon: "-38.48211016122009", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Professor Sila Ribeiro', num: '400', bairro: "Papicu", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "TAIAMA", lat: "-3.74572", lon: "-38.50949", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Silva Paulet', num: '2500', bairro: "Aldeota", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "TERRACES LA MAISON", lat: "-3.72768", lon: "-38.49812", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Osvaldo Cruz', num: '250', bairro: "Meireles", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "TERRACOTA", lat: "-3.73206", lon: "-38.49749", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Perreira Valente', num: '501', bairro: "Meireles", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "THIAGO ALBURQUERQUE", lat: "-3.73937", lon: "-38.50376", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Tibúrcio Cavalcante', num: '1660', bairro: "Aldeota", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "TOSCANA", lat: "-3.81609", lon: "-38.48321", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Travessa Neném', num: '120', bairro: "Cambeba", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "TORRICELI", lat: "-3.73959", lon: "-38.49738", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Leonardo Mota', num: '1520', bairro: "Aldeota", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "TUIUTI", lat: "-3.73259", lon: "-38.50488", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Silva Paulet', num: '856', bairro: "Aldeota", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "VANCOUVER", lat: "-3.8828800413606217", lon: "-38.468035841157764", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Industrial Amílcar Araújo', num: '835', bairro: "Coité", cidade: "Eusébio", sigla: "CE" } },
            { nome: "VENEZA", lat: "-3.74119", lon: "-38.48004", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Joaquim Lim', num: '699', bairro: "Papicu", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "VENEZA", lat: "-3.76725", lon: "-38.53588", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Almirante Rufino', num: '665', bairro: "Vila União", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "VERONA", lat: "-3.87863", lon: "-38.46446", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Nossa Senhora de Nazaré', num: '310', bairro: "Tamatanduba", cidade: "Eusébio", sigla: "CE" } },
            { nome: "VILA EUSÉBIO", lat: "-3.88241", lon: "-38.45585", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Vicente Leitão', num: '819', bairro: "Centro", cidade: "Eusébio", sigla: "CE" } },
            { nome: "VILA ROMANA", lat: "-3.80045", lon: "-38.52946", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Corumbá', num: '479', bairro: "Boa Vista", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "VILAS LOBO", lat: "-3.73212", lon: "-38.46152", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Oliveira FIlho', num: '1680', bairro: "Vicente Pinzon", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "VILLA CENTAURUS", lat: "-3.74799", lon: "-38.49745", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Professor Francisco Gonçalves', num: '355 e 375', bairro: "Dionisio Torres", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "VILLA RICA", lat: "-3.7452825798737215", lon: "-38.50260050848089", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Avenida Antônio Sales', num: '2377', bairro: "Joaquim Tavora", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "VILLA ROMANZA", lat: "-3.7790847628214848", lon: "-38.47912523928778", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Rua do Corrente', num: '317', bairro: "Edson Queiroz", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "VILLAGE ÁGUA FRIA (QUADRA 02)", lat: "-3.77633", lon: "-38.47298", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'F', num: '101', bairro: "Edson Queiroz", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "VILLAGE PORTO REAL", lat: "-3.8209853746938887", lon: "-38.55543574662813", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Rua D', num: '50', bairro: "Parque Dois Irmãos", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "VILLAGE ÁGUA FRIA (QUADRA 01)", lat: "-3.77551", lon: "-38.47273", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'F', num: '50', bairro: "Edson Queiroz", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "VILLAGGIO RAVENNA", lat: "-3.867572344992126", lon: "-38.468976842221174", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Carmelita Rebouças', num: '136', bairro: "Pedra", cidade: "Eusébio", sigla: "CE" } },
            { nome: "VISCONDE DE CAUYPE", lat: "-3.73637", lon: "-38.53483", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Avenida da Universidade', num: '2101', bairro: "Benfica", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "VISCONDE DE MAUÁ", lat: "-3.73046", lon: "-38.49763", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Visconde de Mauá', num: '500', bairro: "Meireles", cidade: "Fortaleza", sigla: "CE" } },
            { nome: "VIRGEM DE FÁTIMA", lat: "-3.73411", lon: "-38.54274", dvr: "", locktec: "FORTALEZA", tipo: "" , end: { rua: 'Bela Cruz', num: '2200', bairro: "Farias Brito", cidade: "Fortaleza", sigla: "CE" } },
            
//      CONDOMÍNIOS DE FORA      

            { nome: "ALAMEDA DOS PINHEIROS VI ", lat: "-8.18753444261896", lon: "-35.57894758910184", dvr: "", locktec: "PERNAMBUCO", tipo: "" , end: { rua: 'Avenida Manoel Santiago de Oliveira', num: '1200', bairro: "Novo Gravatá", cidade: "Gravatá", sigla: "PE" } },
            { nome: "ALTO INGÁ", lat: "-22.903220786176817", lon: "-43.124843368345154", dvr: "", locktec: "RIO DE JANEIRO", tipo: "" , end: { rua: 'Presidente Pedreira', num: '89', bairro: "Ingá", cidade: "Niterói", sigla: "RJ" } },
            { nome: "AROEIRA", lat: "-23.58732", lon: "-46.63271", dvr: "", locktec: "SÃO PAULO", tipo: "" , end: { rua: 'Doutor Neto de Araujo', num: '238', bairro: "Vila Mariana", cidade: "São Paulo", sigla: "SP" } },
            { nome: "ARMANDO RABELO", lat: "-8.045249995904557", lon: "-34.89253349327602", dvr: "", locktec: "PERNAMBUCO", tipo: "" , end: { rua: 'Rui Calaca', num: '94', bairro: "Espinheiro", cidade: "Recife", sigla: "PE" } },
            { nome: "AMALFI", lat: "-23.53027251500084", lon: "-46.71885593828757", dvr: "", locktec: "SÃO PAULO", tipo: "" , end: { rua: 'Princesa Leopoldina', num: '595', bairro: "Alto da Lapa", cidade: "São Paulo", sigla: "SP" } },
            { nome: "BARÃO DA FONTE", lat: "-8.041726170110506", lon: "-34.89484662076417", dvr: "", locktec: "PERNAMBUCO", tipo: "" , end: { rua: 'Rua da Angustura', num: '328', bairro: "Aflitos", cidade: "Recife", sigla: "PE" } },
            { nome: "BARÃO DE MAUÁ", lat: "-22.897848427148332", lon: "-43.28990579602265", dvr: "", locktec: "RIO DE JANEIRO", tipo: "" , end: { rua: 'Paulo Silva Araújo', num: '221', bairro: "Méler", cidade: "Rio de Janeiro", sigla: "RJ" } },
            { nome: "BANDEIRANTE JOÃO DO PRADO", lat: "-22.9745", lon: "-43.1932", dvr: "", locktec: "RIO DE JANEIRO", tipo: "" , end: { rua: 'Pompeu Loureiro', num: '94', bairro: "Copacabana", cidade: "Rio de Janeiro", sigla: "RJ" } },
            { nome: "BARRA ZEN", lat: "-23.00534", lon: "-43.44252", dvr: "", locktec: "RIO DE JANEIRO", tipo: "" , end: { rua: 'Doze', num: '50', bairro: "Recreio dos Bandeirantes", cidade: "Rio de Janeiro", sigla: "RJ" } },
            { nome: "BEACH WAY", lat: "-8.723446735046902", lon: "-35.092617766030266", dvr: "", locktec: "PERNAMBUCO", tipo: "" , end: { rua: 'Euclides da Cunha', num: 'S/N', bairro: "LOT Luiziana QD-J", cidade: "Tamandaré", sigla: "PE" } },
            { nome: "CHAMPS ELYSEES", lat: "-22.92801", lon: "-43.23161", dvr: "", locktec: "RIO DE JANEIRO", tipo: "" , end: { rua: 'Barão de Pirassinunga', num: '33', bairro: "Tijuca", cidade: "Rio de Janeiro", sigla: "RJ" } },
            { nome: "CIDADE DE MONACO", lat: "-8.02963", lon: "-34.91601", dvr: "", locktec: "PERNAMBUCO", tipo: "" , end: { rua: 'Conselheiro Nabuco', num: '246', bairro: "Casa Amarela", cidade: "Recife", sigla: "PE" } },
            { nome: "CASA DOS FLAMBOYANTS", lat: "-22.92772", lon: "-43.22772", dvr: "", locktec: "RIO DE JANEIRO", tipo: "" , end: { rua: 'Rua dos Araujos', num: '105', bairro: "Tijuca", cidade: "Rio de Janeiro", sigla: "RJ" } },
            { nome: "CIUDAD SEVILHA", lat: "-8.02851", lon: "-34.90865", dvr: "", locktec: "PERNAMBUCO", tipo: "" , end: { rua: 'Abel de Sá Bezerra Cavalcanti', num: '74', bairro: "Casa Amarela", cidade: "Recife", sigla: "PE" } },
            { nome: "COSTA AZUL", lat: "-23.63247", lon: "-46.63978", dvr: "", locktec: "SÃO PAULO", tipo: "" , end: { rua: 'Itatiaia', num: '307', bairro: "Vila Guarani (Zona Sul)", cidade: "São Paulo", sigla: "SP" } },
            { nome: "DISEGNO CASAS BOUTIQUE", lat: "-23.01034", lon: "-43.42471", dvr: "", locktec: "RIO DE JANEIRO", tipo: "" , end: { rua: 'Ministro Lafayette Andrada', num: '710', bairro: "Barra da Tijuca", cidade: "Rio de Janeiro", sigla: "RJ" } },
            { nome: "DORMAR", lat: "-8.063112495524258", lon: "-34.877885109719784", dvr: "", locktec: "PERNAMBUCO", tipo: "" , end: { rua: 'Engenheiro Ubaldo Gomes de Matos', num: '53', bairro: "Santo Antônio", cidade: "Recife", sigla: "PE" } },
            { nome: "CONDE DO PARQUE", lat: "-22.961237094918186", lon: "-43.21813321756943", dvr: "", locktec: "RIO DE JANEIRO", tipo: "" , end: { rua: 'Benjamin Batista', num: '197', bairro: "Jardim Botânico", cidade: "Rio de Janeiro", sigla: "RJ" } },
            { nome: "DANIELLE MORAIS", lat: "-8.197871443252662", lon: "-34.918916372750864", dvr: "", locktec: "PERNAMBUCO", tipo: "" , end: { rua: 'Oscar Pereira', num: '37', bairro: "Candeias", cidade: "João dos Guararapes", sigla: "PE" } },
            { nome: "DOMÍNIO LOCKTEC", lat: "-23.61039", lon: "-46.63921", dvr: "", locktec: "SÃO PAULO", tipo: "" , end: { rua: 'Pitangueiras', num: '167', bairro: "Vila Saúde", cidade: "São Paulo", sigla: "SP" } },
            { nome: "DUQUE DANJOU", lat: "-22.98368", lon: "-43.19721", dvr: "", locktec: "RIO DE JANEIRO", tipo: "" , end: { rua: 'Barão da Torre', num: '15', bairro: "Ipanema", cidade: "Rio de Janeiro", sigla: "RJ" } },
            { nome: "ESPAÇOS DOS MANACÁS", lat: "-23.52637", lon: "-46.7068", dvr: "", locktec: "SÃO PAULO", tipo: "" , end: { rua: 'João Anes', num: '144', bairro: "Alto da Lapa", cidade: "São Paulo", sigla: "SP" } },
            { nome: "EDEN", lat: "-23.6353", lon: "-46.6433", dvr: "", locktec: "SÃO PAULO", tipo: "" , end: { rua: 'Carnaubeiras', num: '122', bairro: "Jabaquara", cidade: "São Paulo", sigla: "SP" } },
            { nome: "FAROL DO PORTO", lat: "-8.14013", lon: "-34.90992", dvr: "", locktec: "PERNAMBUCO", tipo: "" , end: { rua: 'Almirante Batista Leão', num: '76', bairro: "Boa Viagem", cidade: "Recife", sigla: "PE" } },
            { nome: "GEOMAR", lat: "-22.97325", lon: "-43.19111", dvr: "", locktec: "RIO DE JANEIRO", tipo: "" , end: { rua: 'Barata Ribeiro', num: '662', bairro: "Copacabana", cidade: "Rio de Janeiro", sigla: "RJ" } },
            { nome: "GAN EDEN", lat: "-22.927222927102637", lon: "-43.25391929854457", dvr: "", tipo: "" , end: { rua: 'Paula Brito', num: '350', bairro: "Andarí", cidade: "RJ", sigla: "Rio de Janeiro" } },
            { nome: "GUARATUBA", lat: "-23.63353", lon: "-46.64242", dvr: "", locktec: "SÃO PAULO", tipo: "" , end: { rua: 'Guaratuba', num: '280', bairro: "Vila Guarani (Zona Sul)", cidade: "São Paulo", sigla: "SP" } },
            { nome: "GUADALUPE", lat: "-8.190494625116312", lon: "-34.921070668892376", dvr: "", locktec: "PERNAMBUCO", tipo: "" , end: { rua: 'Comendador Sá Barreto', num: '365', bairro: "Candeias", cidade: "Jaboatão dos Guararapes", sigla: "PE" } },
            { nome: "FREGUESIA TOWER", lat: "-22.9441", lon: "-43.33552", dvr: "", locktec: "RIO DE JANEIRO", tipo: "" , end: { rua: 'Comandante Rúbens Silva', num: '1000', bairro: "Freguesia (Jacarepaguá)", cidade: "Rio de Janeiro", sigla: "RJ" } },
            { nome: "GUARARAPES", lat: "-8.08301579975463", lon: "-34.98821389363005", dvr: "", locktec: "PERNAMBUCO", tipo: "" , end: { rua: 'Mostarda', num: '3133', bairro: "Curado", cidade: "Jaboatão dos Guararapes", sigla: "PE" } },
            { nome: "HIGH POINT", lat: "-23.62725", lon: "-46.72401", dvr: "", locktec: "SÃO PAULO", tipo: "" , end: { rua: 'Deputado Laércio Corte', num: '753', bairro: "Parque do Morumbi", cidade: "São Paulo", sigla: "SP" } },
            { nome: "IEMANJA", lat: "-8.055557209465272", lon: "-34.877549683914616", dvr: "", locktec: "PERNAMBUCO", tipo: "" , end: { rua: 'Rua da Aurora', num: '1019', bairro: "Santo Amaro", cidade: "Recife", sigla: "PE" } },
            { nome: "ILHA DE CAPRI", lat: "-23.64932", lon: "-46.6349", dvr: "", locktec: "SÃO PAULO", tipo: "" , end: { rua: 'Francisco Duarte Graça', num: '83', bairro: "Cidade Vargas", cidade: "São Paulo", sigla: "SP" } },
            { nome: "ILHA DE KÓS", lat: "-22.93524", lon: "-43.24336", dvr: "", locktec: "RIO DE JANEIRO", tipo: "" , end: { rua: 'Conde de Bonfim', num: '807', bairro: "Tijuca", cidade: "Rio de Janeiro", sigla: "RJ" } },
            { nome: "INOCÊNCIO RODRIGUES", lat: "-8.0294", lon: "-34.90831", dvr: "", locktec: "PERNAMBUCO", tipo: "" , end: { rua: 'Estrada do Arraial', num: '2885', bairro: "Parnamirim", cidade: "Recife", sigla: "PE" } },
            { nome: "LOGOS", lat: "-23.57252", lon: "-46.62561", dvr: "", locktec: "SÃO PAULO", tipo: "" , end: { rua: 'Rua Paulo Orozimbo', num: '584', bairro: "Cambicu", cidade: "São Paulo", sigla: "SP" } },
            { nome: "ITAPUAMA", lat: "-7.99757", lon: "-34.8401", dvr: "", locktec: "PERNAMBUCO", tipo: "" , end: { rua: 'Francisco Ambrósio de Barros Leite', num: '152', bairro: "Bairro Novo", cidade: "Olinda", sigla: "PE" } },
            { nome: "KENSINGTON", lat: "-23.56363153233728", lon: "-46.68095229528178", dvr: "", locktec: "SÃO PAULO", tipo: "" , end: { rua: 'Cônego Eugênio leite', num: '613', bairro: "Pinheiros", cidade: "São Paulo", sigla: "SP" } },
            { nome: "IMPERIAL LARANJEIRAS", lat: "-22.932910962817175", lon: "-43.18574303221055", dvr: "", locktec: "RIO DE JANEIRO", tipo: "" , end: { rua: 'Rua das Laranjeiras', num: '192', bairro: "Laranjeiras", cidade: "Rio de Janeiro", sigla: "RJ" } },
            { nome: "KING DAVID", lat: "-23.649", lon: "-46.64426", dvr: "", locktec: "SÃO PAULO", tipo: "" , end: { rua: 'Rua das Grumixamas', num: '399', bairro: "Vila Parque Jabaquara", cidade: "São Paulo", sigla: "SP" } },
            { nome: "MADONNA DELLE GRAZIE", lat: "-22.889561050705048", lon: "-42.99929046075525", dvr: "", locktec: "RIO DE JANEIRO", tipo: "" , end: { rua: 'Estrada da Paciênia', num: '8069', bairro: "Maria Paula", cidade: "São Gonçalo", sigla: "RJ" } },
            { nome: "MAKAMBIRA", lat: "-8.503826448968212", lon: "-35.00412068058992", dvr: "", locktec: "PERNAMBUCO", tipo: "" , end: { rua: 'Avenida para Praia', num: 'S/N', bairro: "LOT Merepe - V", cidade: "Ipojuca", sigla: "PE" } },
            { nome: "MANOEL VILAÇA", lat: "-8.04207", lon: "-34.94496", dvr: "", locktec: "PERNAMBUCO", tipo: "" , end: { rua: 'Odon Rodrigues de Morais Rego', num: '78', bairro: "Vázea", cidade: "Recife", sigla: "PE" } },
            { nome: "MAQUINÉ", lat: "-22.9325", lon: "-43.24492", dvr: "", locktec: "RIO DE JANEIRO", tipo: "" , end: { rua: 'João Alfredo', num: '25', bairro: "Tijuca", cidade: "Rio de Janeiro", sigla: "RJ" } },
            { nome: "MILENIUM", lat: "-22.93828", lon: "-43.33697", dvr: "", locktec: "RIO DE JANEIRO", tipo: "" , end: { rua: 'Comandante Rúbens Silva', num: '323', bairro: "Freguesia (Jacarepaguá)", cidade: "Rio de Janeiro", sigla: "RJ" } },
            { nome: "MONACO", lat: "-8.13461233383057", lon: "-34.90453341051165", dvr: "", locktec: "PERNAMBUCO", tipo: "" , end: { rua: 'Antônio Passos', num: '51', bairro: "Boa Viagem", cidade: "Recife", sigla: "PE" } },
            { nome: "MORADA DA FONTE", lat: "-8.041835098195657", lon: "-34.89702006753713", dvr: "", locktec: "PERNAMBUCO", tipo: "" , end: { rua: 'Rua da Angustura', num: '104', bairro: "Aflitos", cidade: "Recife", sigla: "PE" } },
            { nome: "NIXXUS I", lat: "-8.50170411915443", lon: "-35.00402127568369", dvr: "", locktec: "PERNAMBUCO", tipo: "" , end: { rua: 'Cajueiro', num: '512', bairro: "Porto de Galinhas", cidade: "Ipojuca", sigla: "PE" } },
            { nome: "OJC", lat: "-23.56727", lon: "-46.64321", dvr: "", locktec: "SÃO PAULO", tipo: "" , end: { rua: 'Martiniano de Carvalho', num: '960', bairro: "Bela Vista", cidade: "São Paulo", sigla: "SP" } },
            { nome: "MARSELLE", lat: "-22.94215", lon: "-43.19284", dvr: "", locktec: "RIO DE JANEIRO", tipo: "" , end: { rua: 'Belisário Távora', num: '231', bairro: "Laranjeiras", cidade: "Rio de janeiro", sigla: "RJ" } },
            { nome: "OSVALDO CORDEIRO DE FARIA", lat: "-8.08365", lon: "-34.93909", dvr: "", locktec: "PERNAMBUCO", tipo: "" , end: { rua: 'Avenida São Paulo', num: '305', bairro: "Jardim São Paulo", cidade: "Recife", sigla: "PE" } },
            { nome: "PAÇO DE SORRENTO", lat: "-23.57246", lon: "-46.63377", dvr: "", locktec: "SÃO PAULO", tipo: "" , end: { rua: 'Castro Alves', num: '908', bairro: "Aclimação", cidade: "São Paulo", sigla: "SP" } },
            { nome: "PIERRE RAMOS", lat: "-7.996434889187311", lon: "-34.84111461580718", dvr: "", locktec: "PERNAMBUCO", tipo: "" , end: { rua: 'Doutor Manoel de Almeida Belo', num: '1241', bairro: "Bairro Novo", cidade: "Olinda", sigla: "PE" } },
            { nome: "POLLUX I", lat: "-23.508661153819066", lon: "-46.66528890641049", dvr: "", locktec: "SÃO PAULO", tipo: "" , end: { rua: 'Praça Delegado Amoroso Neto', num: '120', bairro: "Casa Verde", cidade: "São Paulo", sigla: "SP" } },
            { nome: "PRAÇA DAS AVENÇAS", lat: "-8.05209", lon: "-34.94108", dvr: "", locktec: "PERNAMBUCO", tipo: "" , end: { rua: 'Antônio Curado', num: '307', bairro: "Engenho do Meio", cidade: "Recife", sigla: "PE" } },
            { nome: "PRAÇA DOS FICUS", lat: "-8.05492", lon: "-34.91379", dvr: "", locktec: "PERNAMBUCO", tipo: "" , end: { rua: 'Avenida Caxangá', num: '521', bairro: "Madalena", cidade: "Recife", sigla: "PE" } },
            { nome: "PRAÇA DAS FIGUEIRAS", lat: "-8.05131", lon: "-34.90766", dvr: "", locktec: "PERNAMBUCO", tipo: "" , end: { rua: 'Pessoa de Melo', num: '227', bairro: "Madalena", cidade: "Recife", sigla: "PE" } },
            { nome: "REGINA", lat: "-22.91446", lon: "-43.23152", dvr: "", locktec: "RIO DE JANEIRO", tipo: "" , end: { rua: 'Isidro de Figueredo', num: '31', bairro: "Maracanã", cidade: "Rio de Janeiro", sigla: "RJ" } },
            { nome: "REQUINTE DO RIO", lat: "-22.91936", lon: "-43.22433", dvr: "", locktec: "RIO DE JANEIRO", tipo: "" , end: { rua: 'Pereira de Siqueira', num: '15', bairro: "Tijuda", cidade: "Rio de Janeiro", sigla: "RJ" } },
            { nome: "PRAIA LEME", lat: "-22.96139248361552", lon: "-43.16539317370994", dvr: "", locktec: "RIO DE JANEIRO", tipo: "" , end: { rua: 'Praça Almirante Júlio de Noronha', num: 'S/N', bairro: "Leme", cidade: "Rio de Janeiro", sigla: "RJ" } },
            { nome: "RESIDENCIAL BARÃO", lat: "-23.5326", lon: "-46.6491", dvr: "", locktec: "SÃO PAULO", tipo: "" , end: { rua: 'Alameda Barão de Limeira', num: '1052', bairro: "Campos Elíseos", cidade: "São Paulo", sigla: "SP" } },
            { nome: "RIO VERDE", lat: "-23.52636", lon: "-46.70524", dvr: "", locktec: "SÃO PAULO", tipo: "" , end: { rua: 'Luís Martins', num: '5', bairro: "Alto da Lapa", cidade: "São Paulo", sigla: "SP" } },
            { nome: "RITA OLYNTHO MACHADO", lat: "-22.986260934399642", lon: "-43.19581332701876", dvr: "", locktec: "RIO DE JANEIRO", tipo: "" , end: { rua: 'Avenida Rainha Elizabeth da Bélgica', num: '664', bairro: "Ipanema", cidade: "Rio de Janeiro", sigla: "RJ" } },
            { nome: "SAINT TROPEZ", lat: "-22.904761195784843", lon: "-43.11400916420489", dvr: "", locktec: "RIO DE JANEIRO", tipo: "" , end: { rua: 'travessa Coelho Gomes', num: '10', bairro: "Icaraí", cidade: "Niterói", sigla: "RJ" } },
            { nome: "SÃO DOMINGOS", lat: "-22.90049", lon: "-43.12792", dvr: "", locktec: "RIO DE JANEIRO", tipo: "" , end: { rua: 'General Andrade Neves', num: '317', bairro: "São Domingos", cidade: "Niterói", sigla: "RJ" } },
            { nome: "SÃO CAETANO", lat: "-8.11306", lon: "-35.29239", dvr: "", locktec: "PERNAMBUCO", tipo: "" , end: { rua: 'Cândido Cardoso Fontes', num: '87', bairro: "Matriz", cidade: "Vitória de Santo Antão", sigla: "PE" } },
            { nome: "SPLENDOR TABOÃO", lat: "-23.604236269402016", lon: "-46.759424618813", dvr: "", locktec: "SÃO PAULO", tipo: "" , end: { rua: 'Rua das Magnólias', num: '17', bairro: "parque Assunção", cidade: "Taboão da Serra", sigla: "SP" } },
            { nome: "SÃO JUDAS PARK", lat: "-23.624544254102528", lon: "-46.641301323955034", dvr: "", locktec: "SÃO PAULO", tipo: "" , end: { rua: 'Ararapira', num: '320', bairro: "Planalto Paulista", cidade: "São Paulo", sigla: "SP" } },
            { nome: "STUDIO ONE CLASSIC", lat: "-8.142475046201215", lon: "-34.908456810646", dvr: "", locktec: "PERNAMBUCO", tipo: "" , end: { rua: 'Sá e Souza', num: '1205', bairro: "Boa Viagem", cidade: "Recife", sigla: "PE" } },
            { nome: "SIBIPIRUNAS", lat: "-22.94333", lon: "-43.03432", dvr: "", locktec: "RIO DE JANEIRO", tipo: "" , end: { rua: 'Sibipirunas', num: '138', bairro: "Maravista", cidade: "Niterói", sigla: "RJ" } },
            { nome: "SUNNY SIDE", lat: "-22.45894350440232", lon: "-43.15664489207349", dvr: "", locktec: "RIO DE JANEIRO", tipo: "" , end: { rua: 'Estrada do Carangola', num: '1953', bairro: "Carangola", cidade: "Petrópolis", sigla: "RJ" } },
            { nome: "SÓRIA", lat: "-8.13138", lon: "-34.90224", dvr: "", locktec: "PERNAMBUCO", tipo: "" , end: { rua: 'Avenida Engenheiro Domingos Ferreira', num: '5027', bairro: "Boa Viagem", cidade: "Recife", sigla: "PE" } },
            { nome: "TIMONEIRO", lat: "-8.13692", lon: "-34.90273", dvr: "", locktec: "PERNAMBUCO", tipo: "" , end: { rua: 'Setúbal', num: '682', bairro: "Boa Viagem", cidade: "Recife", sigla: "PE" } },
            { nome: "TAIO", lat: "-8.05743", lon: "-34.93016", dvr: "", locktec: "PERNAMBUCO", tipo: "" , end: { rua: 'Taió', num: '201', bairro: "Cordeiro", cidade: "Recife", sigla: "PE" } },
            { nome: "TOUR DEL PANE", lat: "-22.907605098107435", lon: "-43.13092025666666", dvr: "", locktec: "RIO DE JANEIRO", tipo: "" , end: { rua: 'Vera Crispino de Freitas', num: '48', bairro: "Boa Viagem", cidade: "Niterói", sigla: "RJ" } },
            { nome: "TRAVESSA BOLÍVIA", lat: "-22.894625668728285", lon: "-43.03590365283335", dvr: "", locktec: "RIO DE JANEIRO", tipo: "" , end: { rua: 'Travessa Bolívia', num: '31', bairro: "Vila Progresso", cidade: "Niterói", sigla: "RJ" } },
            { nome: "TUMIARÚ", lat: "-23.58554", lon: "-46.63503", dvr: "", locktec: "SÃO PAULO", tipo: "" , end: { rua: 'Dona Inácia Uchôa', num: '52', bairro: "Vila Mariana", cidade: "São Paulo", sigla: "SP" } },
            { nome: "VERA CRUZ", lat: "-22.97315", lon: "-43.19108", dvr: "", locktec: "RIO DE JANEIRO", tipo: "" , end: { rua: 'Barata Ribeiro', num: '658', bairro: "Copacabana", cidade: "Rio de Janeiro", sigla: "RJ" } },
            { nome: "VALPARAÍSO", lat: "-22.52024", lon: "-43.19461", dvr: "", locktec: "RIO DE JANEIRO", tipo: "" , end: { rua: 'Avenida Portugal', num: '415', bairro: "Valparaíso", cidade: "Petrópolis", sigla: "RJ" } },
            { nome: "VIAREGGIO", lat: "-23.6288", lon: "-46.63533", dvr: "", locktec: "SÃO PAULO", tipo: "" , end: { rua: 'Rua dos Democratas', num: '721', bairro: "Vila Monte Alegre", cidade: "São Paulo", sigla: "SP" } },
            { nome: "VILA DO CONDE", lat: "-8.086331483974359", lon: "-34.95706926176628", dvr: "", locktec: "PERNAMBUCO", tipo: "" , end: { rua: 'João Ferreira', num: '70', bairro: "Sancho", cidade: "Recife", sigla: "PE" } },
            { nome: "VILLAGE DAS PEDRAS", lat: "-22.931384128789055", lon: "-42.89823197332009", dvr: "", locktec: "RIO DE JANEIRO", tipo: "" , end: { rua: 'Doutor Creso Ribeiro', num: 'S/N', bairro: "São José do Imbassaí", cidade: "Maricá", sigla: "RJ" } },
            { nome: "VIRGINIA", lat: "-8.12017", lon: "-34.89838", dvr: "", locktec: "PERNAMBUCO", tipo: "" , end: { rua: 'Avenida Engenheiro Domingos Ferreira', num: '3652', bairro: "Boa Viagem", cidade: "Recife", sigla: "PE" } },
            { nome: "VIVENDAS DO MARACANÃ", lat: "-22.91485", lon: "-43.23143", dvr: "", locktec: "RIO DE JANEIRO", tipo: "" , end: { rua: 'Isidro de Figueiredo', num: '26', bairro: "Maracanã", cidade: "Rio de Janeiro", sigla: "RJ" } },
            { nome: "VILLA DI NAPOLE", lat: "-22.92388", lon: "-43.3582", dvr: "", locktec: "RIO DE JANEIRO", tipo: "" , end: { rua: 'Alexandre Ramos', num: '535', bairro: "Pechincha", cidade: "Rio de Janeiro", sigla: "RJ" } },
        ]
    }

//  FUNÇÕES

    getCond () {
        return this.arrayCond
    }
    getCondLength(){
        return this.arrayCond.length
    }

    transformarArray (id) {
        const box = document.querySelector(`#${id}`)
        box.innerHTML = ''
        this.arrayCond.forEach( el => {
            let cod = ''
            if(!el.dvr){
                cod = 'dvr: "", '
            }else {
                cod = `dvr: "${el.DVR}", `
            }
            if (el.locktec) {
                cod += `locktec: "${el.locktec}", `
            }else if(el.end.sigla === "CE" && !el.locktec){
                cod += 'locktec: "FORTALEZA", '
            }else if (el.end.sigla === "SP" && !el.locktec) {
                cod += 'locktec: "SÃO PAULO", '
            }else if (el.end.sigla === "RJ" && !el.locktec) {
                cod += 'locktec: "RIO DE JANEIRO", '
            }else if (el.end.sigla === "PE" && !el.locktec) {
                cod += 'locktec: "PERNAMBUCO", '
            }

            if(el.tipo){
                cod += `tipo: "${el.tipo}" ,`
            }else {
                cod += `tipo: "" ,`
            }

            box.innerHTML += `{ nome: "${el.nome}", lat: "${el.lat}", lon: "${el.lon}", ${cod} end: { rua: '${el.end.rua}', num: '${el.end.num}', bairro: "${el.end.bairro}", cidade: "${el.end.cidade}", sigla: "${el.end.sigla}" } },<br>`
        })
    }

    nomeSimples (nome) {
        return nome.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').trim()
    }

    buscar (atributo,buscar) {
        return this.arrayCond.filter( obj => this.nomeSimples(obj[atributo]).includes(this.nomeSimples(buscar)) )
    }
}